
AGENT_NAME: str = "agent_name"
AGENT_METHOD_NAME: str = "agent_method_name"
TASK_NAME: str = "task_name"
DEPENDS_ON: str = "depends_on"
REQUIRES_INPUT: str = "requires_input"
PRODUCES_OUTPUT: str = "produces_output"
MAX_RETRIES: str = "max_retries"
RETRIES_LEFT: str = "retries_left"
TASK_STATUS: str = "task_status"

LOCAL_FILE_TYPE: str = "local_file"

STATUS_PENDING: str = "PENDING"
STATUS_IN_PROGRESS: str = "IN PROGRESS"
STATUS_SUCCESS: str = "SUCCESS"
STATUS_FAILED: str = "FAILED"
STATUS_RETRIED: str = "RETRIED"

ANSI_COLOR_RESET: str = "\033[0m"
ANSI_COLOR_GREEN: str = "\033[92m"
ANSI_COLOR_ORANGE: str = "\033[93m"
ANSI_COLOR_RED: str = "\033[91m"
ANSI_COLOR_CYAN: str = "\033[96m"
ANSI_COLOR_GRAY: str = "\033[90m"
